notify: &notify
  - stdout: ~
  - kanbantool: {board_id: 244160, workflow_stage_id: 1870778, card_type_id: 2789788, swimlane_id: 572100}
  - slack: {main_c: '#bot_disponibilidade', secondary_c: '#bot_disponibilidade5m'}
  - telegram: -105669580

checkers:
  - name: SISPRENATAL
    url: http://sisprenatal.saude.gov.br/login.jsf
    notify: 
      - *notify
    status: 200
    body: SISPRENATAL
    min_failures: 3 
    
  - name: SINAN
    url: http://sinan.saude.gov.br/sinan/login/login.jsf
    notify: 
      - *notify
    status: 200
    body: SINAN
    min_failures: 3
    
  - name: SARGSUS
    url: http://sargsus.saude.gov.br/sargsus/login!carregarPagina.action
    notify: 
      - *notify
    status: 200
    body: Gestores SUS
    min_failures: 3 

  - name: SISCAN
    url: http://siscan.saude.gov.br/login.jsf
    notify: 
      - *notify
    status: 200
    body: SISCAN
    min_failures: 3

  - name: HEMOVIDA
    url: http://hemovida.saude.gov.br/
    notify: 
      - *notify
    status: 200
    body: HEMOVIDA
    min_failures: 3

  - name: HORUS
    url: http://horus.saude.gov.br/horus/css/geral.css
    notify: 
      - *notify
    status: 200
    body: sistema
    min_failures: 3

  - name: MAISMEDICOS
    url: http://maismedicos.saude.gov.br/new/web/app.php/maismedicos/rms
    notify: 
      - *notify
    status: 200
    body: Mais Médicos
    min_failures: 3 

  - name: SCAWEB
    url: http://scaweb.saude.gov.br:9443/scaweb/
    notify: 
      - *notify
    status: 200
    body: SCAWEB
    min_failures: 3 

  - name: SNT
    url: https://snt.saude.gov.br/consulta/ConsultaReceptorPA.aspx
    notify: 
      - *notify
    status: 200
    body: Consulta à Situação no Cadastro Técnico de Pâncreas
    min_failures: 3 

  - name: SCPAWS
    url: http://aplicacao.saude.gov.br/datasus-scpa-ws/ScpaServiceImpl?wsdl
    notify: 
      - *notify
    status: 200
    body: ScpaService
    min_failures: 3 

  - name: PLATAFORMA BR
    url: http://aplicacao.saude.gov.br/plataformabrasil/login.jsf
    notify: 
      - *notify
    status: 200
  #  body: PLATAFORMA BRASIL
    min_failures: 3 

  - name: SIGESP
    url: http://sigesp.saude.gov.br/portal\#/login
    notify: 
      - *notify
    status: 200
    body: SIGESP
    min_failures: 3

  - name: FARMACIA POPULAR
    url: https://200.214.130.55:9443/farmaciapopular/services/ServicoSolicitacaoWS?wsdl
    notify: 
      - *notify
    status: 200
 #   body: ???
    min_failures: 3 

  - name: REDECORPSUS
    url: http://redecorpsus.saude.gov.br/MS/login
    notify: 
      - *notify
    status: 200
    body: suporteredecorpsus@saude.gov.br
    min_failures: 3

  - name: CADSUS WS
    url: https://servicos.saude.gov.br/cadsus/CadsusService/v5r0?wsdl
    notify: 
      - *notify
    status: 200
    body: requestPesquisar
    min_failures: 3 

  - name: PORTAL DO CIDADAO
    url: https://portaldocidadao.saude.gov.br/portalcidadao/
    notify: 
      - *notify
    status: 200
    body: Portal de Saúde do Cidadão
    min_failures: 3 

  - name: SPO
    url: http://aplicacao.saude.gov.br/spo/login.jsf
    notify: 
      - *notify
    status: 200
    body: SPO
    min_failures: 3 

  - name: OUVIDORSUS
    url: http://ouvprod01.saude.gov.br/ouvidor/LoginAtendimento.do
    notify: 
      - *notify
    status: 200
    body: OuvidorSus
    min_failures: 3 

  - name: OUVIDORSUS
    url: http://ouvprod02.saude.gov.br/ouvidor/LoginAtendimento.do
    notify: 
      - *notify
    status: 200
    body: OuvidorSus
    min_failures: 3 

  - name: SIGTAP
    url: http://sigtap.datasus.gov.br/tabela-unificada/app/sec/inicio.jsp
    notify: 
      - *notify
    status: 200
    body: Acessar a Tabela Unificada
    min_failures: 3 

  - name: SIPNI
    url: http://sipni.datasus.gov.br/si-pni-web/faces/duvida/duvidaSipni.jsf
    notify: 
      - *notify
    status: 200
    body: SI-PNI
    min_failures: 3 

  - name: FNS-INDICAÇÃO OBJETO
    url: http://proposta.saude.gov.br/loginEntidade.jsf
    notify: 
      - *notify
    status: 200
    body: PROPOSTAS
    min_failures: 3 

  - name: FNSDOC
    url: http://fnsdoc.saude.gov.br/
    notify: 
      - *notify
    status: 200
   # body: PROPOSTAS
    min_failures: 3

  - name: BGSICONVWS
    url: http://bgsiconvws.saude.gov.br/bgsiconvws/
    notify: 
      - *notify
    status: 200
    body: BGSiconvWS
    min_failures: 3

  - name: SIAFIWS
    url: http://siafiws.saude.gov.br/siafiws/services/InterfaceWS
    notify: 
      - *notify
    status: 200
    body: InterfaceWS
    min_failures: 3

  - name: FNS-INDICAÇÃO EMENDA
    url: http://emenda.saude.gov.br/loginIndicacaoEmenda.jsf
    notify: 
      - *notify
    status: 200
    body: emendas
    min_failures: 3 

  - name: FNS-PORTAL
    url: http://www.fns.saude.gov.br/indexExterno.jsf
    notify: 
      - *notify
    status: 200
    body: FNS
    min_failures: 3

 # - name: SISGERF(Sem acesso ao serviço) 
 #   url: ????
 #   notify: 
 #     - *notify
 #     - email:
 #   status: 200
 #   body: ???
 #   min_failures: 3   

  - name: CNES
    url: http://cnes.datasus.gov.br/
    notify: 
      - *notify
    status: 200
    body: CNES
    min_failures: 3

  - name: APPGALRN
    url: https://gal.riodejaneiro.sus.gov.br/
    notify: 
      - *notify
    status: 200
    body: gal.riodejaneiro.sus.gov.br
    min_failures: 3 

  - name: SDA (Albatross Admin)
    url: http://sda.saude.gov.br/albatross-admin/
    notify: 
      - *notify
    status: 200
    body: Bem-vindo!
    min_failures: 3 

  - name: SDA (Agendador)
    url: http://sda.saude.gov.br/agendador/securityRealm/commenceLogin?from=%2Fagendador%2F
    notify: 
      - *notify
    status: 200
    min_failures: 3
 
  - name: SDA (Farmacia Popular)
    url: http://sda.saude.gov.br/
    notify:
      - *notify
    status: 200
    min_failures: 3


#-----------------------------------------DCRUM----------------------------------------

  - name: SISREG NACIONAL
    url: http://sisregiii.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG ALAGOAS
    url: http://sisregiiial.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG PERNAMBUCO
    url: http://sisregiiipe.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG NORDESTE
    url: http://sisregiiinordeste.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG NORTE
    url: http://sisregiiinorte.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG RIO DE JANEIRO
    url: http://sisregiiirj.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG SANTA CATARINA
    url: http://sisregiiisc.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG SÃO PAULO
    url: http://sisregiiisp.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG CENTRO OESTE
    url: http://sisregiiicentrooeste.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 

  - name: SISREG MANAUS
    url: http://sisregiii-manaus.saude.gov.br/
    notify: 
      - *notify
      - email: marco.porto@xys.com.br
    status: 200
    body: NACIONAL
    min_failures: 3 
